"""users table

Revision ID: df29ff7303e1
Revises: 27ba890e3d85
Create Date: 2019-10-16 09:34:25.019420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df29ff7303e1'
down_revision = '27ba890e3d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=64), nullable=True),
    sa.Column('Artist', sa.String(length=120), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_song_Artist'), 'song', ['Artist'], unique=True)
    op.create_index(op.f('ix_song_Name'), 'song', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_Name'), table_name='song')
    op.drop_index(op.f('ix_song_Artist'), table_name='song')
    op.drop_table('song')
    # ### end Alembic commands ###
